/**
 * @file Code Explainer screen component.
 * Allows users to paste code snippets and receive detailed explanations generated by an on-device LLM.
 * Built using the react-native-executorch library.
 */

// React
import React from 'react';

// React Native
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  ScrollView,
  KeyboardAvoidingView,
  Platform,
} from 'react-native';

// Components
import ModelLoader from '../../components/ModelLoader';

// Hooks
import { useCodeExplainer } from './useCodeExplainer';

// Constants
import { SAMPLE_CODE, TIPS } from './CodeExplainer.constants';

// Styles
import { styles } from './CodeExplainer.styles';

/**
 * CodeExplainerScreen component.
 * Renders a specialized code input field with monospaced font and a generated explanation card.
 * 
 * @returns {React.FC} The rendered Code Explainer screen.
 */
const CodeExplainerScreen: React.FC = () => {
  const {
    code,
    setCode,
    explanation,
    setExplanation,
    llm,
    handleExplain,
  } = useCodeExplainer();

  return (
    <KeyboardAvoidingView
      style={styles.container}
      behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
      keyboardVerticalOffset={Platform.OS === 'ios' ? 90 : 0}>
      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.content}
        keyboardShouldPersistTaps="handled">

        <View style={styles.statusRow}>
          <ModelLoader
            downloadProgress={llm.downloadProgress}
            isReady={llm.isReady}
            error={llm.error ? llm.error.message : null}
            modelName="SmolLM 2.1 135M"
          />
        </View>

        <Text style={styles.label}>Paste your code</Text>
        <TextInput
          style={styles.codeInput}
          value={code}
          onChangeText={text => {
            setCode(text);
            setExplanation('');
          }}
          placeholder="// Paste any code snippet here…"
          placeholderTextColor="#888"
          multiline
          textAlignVertical="top"
          autoCapitalize="none"
          autoCorrect={false}
          spellCheck={false}
          editable={!llm.isGenerating}
        />

        <View style={styles.buttonRow}>
          <TouchableOpacity
            style={styles.sampleBtn}
            onPress={() => {
              setCode(SAMPLE_CODE);
              setExplanation('');
            }}>
            <Text style={styles.sampleBtnText}>Load sample</Text>
          </TouchableOpacity>

          <TouchableOpacity
            style={[
              styles.explainBtn,
              (!code.trim() || !llm.isReady || llm.isGenerating) &&
                styles.btnDisabled,
            ]}
            onPress={llm.isGenerating ? () => llm.interrupt() : handleExplain}
            disabled={!llm.isReady || (!code.trim() && !llm.isGenerating)}>
            <Text style={styles.explainBtnText}>
              {llm.isGenerating ? '■ Stop' : 'Explain code'}
            </Text>
          </TouchableOpacity>
        </View>

        {explanation.length > 0 && (
          <View style={styles.outputCard}>
            <View style={styles.outputHeader}>
              <Text style={styles.outputLabel}>Explanation</Text>
              <View style={styles.onDeviceBadge}>
                <Text style={styles.onDeviceBadgeText}>⚡ On-Device</Text>
              </View>
            </View>
            <Text style={styles.outputText}>{explanation}</Text>
          </View>
        )}

        {!explanation && !llm.isGenerating && llm.isReady && (
          <View style={styles.tipsCard}>
            <Text style={styles.tipsTitle}>Tips</Text>
            {TIPS.map((tip, i) => (
              <Text key={i} style={styles.tipText}>
                • {tip}
              </Text>
            ))}
          </View>
        )}
      </ScrollView>
    </KeyboardAvoidingView>
  );
};

export default CodeExplainerScreen;
