package com.margelo.nitro.nitromodulesdemo

import com.margelo.nitro.core.Promise
import java.util.concurrent.ConcurrentHashMap

/**
 * UserModule implementation in Kotlin.
 * Nitro handles the conversion from JS objects/enums to Kotlin data classes/enums.
 */
class UserModule : HybridUserModuleSpec() {
  // Simple in-memory storage using a thread-safe map
  private val users = ConcurrentHashMap<String, User>()

  override fun registerUser(user: User) {
    users[user.id] = user
    println("Native [Kotlin]: Registered user ${user.name} with role ${user.role}")
  }

  override fun getUserById(id: String): User? {
    return users[id]
  }

  override fun getUsersByRole(role: UserRole): Array<User> {
    // Filter the users by role and return as an array
    return users.values.filter { it.role == role }.toTypedArray()
  }

  override fun fetchRemoteUser(id: String): Promise<User> {
    return Promise.async {
      // Simulate some asynchronous fetch with a delay
      Thread.sleep(1200)
      
      // Constructing a Kotlin User data class (generated by Nitrogen)
      User(
        id = id, 
        name = "Fetch $id", 
        age = 30.0, // age is Double because JS number is Double in Kotlin
        role = UserRole.ADMIN, 
        tags = arrayOf("fetched", "remote", "nitro")
      )
    }
  }

  override fun clearAll() {
    users.clear()
    println("Native [Kotlin]: Cleared all users")
  }
}
